### ISSUE TITLE
Change the TextColor of a Picker Component

### ISSUE THREAD

**Issue by NikoMontana** [wix/react-native-ui-lib#136]
Hi, first of all the picker works great and it gives me a the abillity to learn react native, but how should I   change the text color, fontsize of the selected item in the TextInput Component of the Picker? 

Edit: also how would you remove the underline?

**Comment by ethanshar** [comment]
`Picker` inherits `TextInput` therefore removing the underline is done by passing true to`hideUnderline` prop.
I fixed an issue, now you can pass style to the picker. try using it to change color, fontSize

**Comment by NikoMontana** [comment]
Thank you very much! The problem was solved with your solution regarding the underline.

But setting the color prop in style prop, doesnt do anything. Here is my code..

```                
                      <Picker
                        hideUnderline
                        style={styles.categoryPicker}
                        value={this.state.task_posting_category}
                        enableModalBlur={false}
                        onChange={item =>
                          this.setState({
                            task_posting_category: item,
                            task_category_image:
                              task_category_images[item.value]
                          })
                        }
                        topBarProps={{ title: "Category" }}
                      >
                        {_.map(task_category, option => (
                          <Picker.Item
                            key={option.value}
                            value={option}
                            disabled={option.disabled}
                          />
                        ))}
                      </Picker>


  categoryPicker: {
    color: "white"
  }

**Comment by ethanshar** [comment]
Hey @NikoMontana, 
In this example it works 
https://github.com/wix/react-native-ui-lib/blob/master/demo/src/screens/componentScreens/FormScreen.js#L110

**Comment by ethanshar** [comment]
Hey @NikoMontana, is this still relevant ?

**Comment by NikoMontana** [comment]
Hi, @ethanshar sorry for the late response. Yes it is still relevant, the textcolor and fontsize are still not changeable.

**Comment by Inbal-Tish** [comment]
@NikoMontana Hi. I see that in your example you are trying to pass 'color' in the style object, that should affect the color of the TextInput text. Since this is a picker, the onPress is opening a modal, thus the text color is irrelevant. Try to pass 'backgroundColor: "red"' to see if that works for you. Anyways, let me know what is that you're trying to modify and I might be able to guide you better. Btw, instead of passing 'enableModalBlur={false}' you can remove this prop altogether.

**Comment by kallayyash** [comment]
> Thank you very much! The problem was solved with your solution regarding the underline.
> 
> But setting the color prop in style prop, doesnt do anything. Here is my code..
> 
> ```
>                       <Picker
>                         hideUnderline
>                         style={styles.categoryPicker}
>                         value={this.state.task_posting_category}
>                         enableModalBlur={false}
>                         onChange={item =>
>                           this.setState({
>                             task_posting_category: item,
>                             task_category_image:
>                               task_category_images[item.value]
>                           })
>                         }
>                         topBarProps={{ title: "Category" }}
>                       >
>                         {_.map(task_category, option => (
>                           <Picker.Item
>                             key={option.value}
>                             value={option}
>                             disabled={option.disabled}
>                           />
>                         ))}
>                       </Picker>
> 
> 
>   categoryPicker: {
>     color: "white"
>   }
> ```

how to Done Text selected value on dropdown

**Comment by kallayyash** [comment]
Sorry i have one question to everyone "How to add Done Text in dropdown selected value"

**Comment by trentmercer** [comment]
Having this same issue still. Here's what i've tried with no success: 

`  <Picker
                                style={{ color: 'black' }}
                                color={'black'}
                                labelColor={'black'}
                                labelStyle={{ color: 'black', backgroundColor: 'black'}}
                                
                                hideUnderline
                                placeholder="Select a Career Industry"
                                onChange={(value: string) => { setBio({ ...bio, career: value }) }}
                                value={bio?.career}
                                useNativePicker
                            >
                                {_.map(careers, (option: any) => (
                                    <Picker.Item key={option.value} value={option.value} label={option.label} disabled={option.disabled} />
                                ))}
                            </Picker>
`

**Comment by brentrbutcher** [comment]
Did you ever find out the answer to this? I am struggling currently as well
