### ISSUE TITLE
Expo Demo App outdated

### ISSUE THREAD

**Issue by ejkkan** [wix/react-native-ui-lib#2295]
The app linked to the QRcode in the readme is outdated.
"The project uses SDK 42.0.0" But the recent builds of the Expo Go app only supports <44.0.0

**Comment by JCharante** [comment]
This is somewhat related to #2199 , actually if you open the snack link and change the expo version to v44.0 you'll be able to run it.

**Comment by merganon** [comment]
As of today you can't pick v44 anymore

![image](https://user-images.githubusercontent.com/74573436/201330680-b1f3d546-4cdc-47b2-ab5f-514662da03ca.png)

**Comment by BenMorel** [comment]
Minimum Expo version is now `45.0.0`. Any plans to update the QR code?

@JCharante The QR code points to `exp://expo.dev/@ethanshar/rnuilib`, which has an https counterpart at https://expo.dev/@ethanshar/rnuilib, where can I find the corresponding Snack link please?

**Comment by BenMorel** [comment]
Oh, and the one found on https://wix.github.io/react-native-ui-lib/ :
https://snack.expo.dev/@ethanshar/rnuilib_snack?platform=ios&supportedPlatforms=ios,android

Fails with:

![image](https://user-images.githubusercontent.com/1952838/210024969-39f66333-2467-47fb-82ef-3dda750fe366.png)

**Comment by alicanto-parloa** [comment]
> Oh, and the one found on https://wix.github.io/react-native-ui-lib/ : https://snack.expo.dev/@ethanshar/rnuilib_snack?platform=ios&supportedPlatforms=ios,android
> 
> Fails with:
> 
> ![image](https://user-images.githubusercontent.com/1952838/210024969-39f66333-2467-47fb-82ef-3dda750fe366.png)

Same issue!

**Comment by HarunKilic** [comment]
Sadly the library is not testable which makes many jump off. 
Would be nice if this got fixed, so users can test and see the capability of the project.

**Comment by DigitalLeaves** [comment]
+1

**Comment by MaxInMoon** [comment]
+10

**Comment by hafridi** [comment]
+1 as someone trying to use this for the first time, this should be resolved as soon as possible so people like me can see it in action

**Comment by my3t** [comment]
+1

**Comment by BenMorel** [comment]
Still relevant I guess.

**Comment by HarunKilic** [comment]
Even bot gave up

**Comment by BenMorel** [comment]
Expo app still broken:

![Expo](https://github.com/wix/react-native-ui-lib/assets/1952838/785b894d-c333-474c-8d30-0feddfe4cc9f)

This should be reopened.

**Comment by BenMorel** [comment]
I'm still getting the same error 403 as in the screenshot above. Did I miss something?

**Comment by pascalito007** [comment]
guys! please fixe the demo
